Detect when git mbr is failing

diff --git a/linux/bin/git-mbr b/linux/bin/git-mbr
--- a/linux/bin/git-mbr
+++ b/linux/bin/git-mbr
@@ -1,3 +1,13 @@
 #!/usr/bin/sh
 
-git symbolic-ref refs/remotes/origin/HEAD | sed 's@^refs/remotes/origin/@@'
+REF_NAME=$(git symbolic-ref refs/remotes/origin/HEAD 2>/dev/null)
+REF_SUCCESS=$?
+
+if [ $REF_SUCCESS -ne 0 ]; then
+    >&2 echo "$PWD: Failed to determine main branch.";
+    >&2 echo "You may need to set the head of the origin.";
+    >&2 echo "try: git remote set-head origin main";
+    exit $REF_SUCCESS;
+fi
+
+echo "$REF_NAME" | sed 's@^refs/remotes/origin/@@'
