maybe-yarn: Check if yarn is in the path

diff --git a/linux/bin/maybe-yarn b/linux/bin/maybe-yarn
--- a/linux/bin/maybe-yarn
+++ b/linux/bin/maybe-yarn
@@ -1,5 +1,10 @@
 #!/usr/bin/bash
 
+if ! which yarn; then
+    echo "maybe-yarn: Could not find yarn in your path";
+    exit 1;
+fi
+
 if [ -f "package.json" ]; then
     yarn $*;
 else
